In [1]:
import numpy

In [2]:
array = numpy.arange(27)# 

In [3]:
type(array)

numpy.ndarray

In [4]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
array.reshape(3,9)#convert existing array into multi dimensional.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
array.reshape(3,3,3)#3d array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
import cv2

In [8]:
image = cv2.imread('smallgray.png',0)# 0 for reading grey image & 1 for reading BGR..
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
image = cv2.imread('smallgray.png',1)# creates a transpose matrics
image# this will creates a 3d matrics of each pixle of grey image with their BGR values repectivly...

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
image2=cv2.imwrite('new_smallgray.png',image)
image2

True

In [11]:
image2 = cv2.imread('new_smallgray.png',0)
image2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
image2[0:2,2] # indexing numpy array..

array([104, 255], dtype=uint8)

In [13]:
for i in image2: #iterates array by row..
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [14]:
for i in image2.T:#iterates trough column by transpose the array matrics
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [15]:
for i in image2.flat: # iterate value by value...
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [16]:
array1 = numpy.arange(15) # create a new array with similar size of 'image2'....
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
new = array1.reshape(3,5)
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
new

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
array_merge = numpy.hstack((new,image2))# concatinate both arrays Horizontally & and create a new one.... 
array_merge

array([[  0,   1,   2,   3,   4, 187, 158, 104, 121, 143],
       [  5,   6,   7,   8,   9, 198, 125, 255, 255, 147],
       [ 10,  11,  12,  13,  14, 209, 134, 255,  97, 182]])

In [21]:
array_mergeV = numpy.vstack((new,image2))# concatinate both arrays Vertically & and create a new one.... 
array_mergeV

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]])

In [22]:
array_mergeV.shape[0]# counts the row 

6

In [23]:
split_array= numpy.hsplit(image,5)
print(split_array)



[array([[[187, 187, 187]],

       [[198, 198, 198]],

       [[209, 209, 209]]], dtype=uint8), array([[[158, 158, 158]],

       [[125, 125, 125]],

       [[134, 134, 134]]], dtype=uint8), array([[[104, 104, 104]],

       [[255, 255, 255]],

       [[255, 255, 255]]], dtype=uint8), array([[[121, 121, 121]],

       [[255, 255, 255]],

       [[ 97,  97,  97]]], dtype=uint8), array([[[143, 143, 143]],

       [[147, 147, 147]],

       [[182, 182, 182]]], dtype=uint8)]
