In [1]:
import numpy

In [2]:
array = numpy.arange(27)# 

In [3]:
type(array)

numpy.ndarray

In [4]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
array.reshape(3,9)#convert existing array into multi dimensional.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
array.reshape(3,3,3)#3d array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
import cv2

ImportError: No module named cv2

In [ ]:
image = cv2.imread('smallgray.png',0)# 0 for reading grey image & 1 for reading BGR..
image

In [ ]:
image = cv2.imread('smallgray.png',1)# creates a transpose matrics
image# this will creates a 3d matrics of each pixle of grey image with their BGR values repectivly...

In [ ]:
image2=cv2.imwrite('new_smallgray.png',image)
image2

In [ ]:
image2 = cv2.imread('new_smallgray.png',0)
image2

In [ ]:
image2[0:2,2] # indexing numpy array..

In [ ]:
for i in image2: #iterates array by row..
    print(i)

In [ ]:
for i in image2.T:#iterates trough column by transpose the array matrics
    print(i)

In [ ]:
for i in image2.flat: # iterate value by value...
    print(i)

In [ ]:
array1 = numpy.arange(15) # create a new array with similar size of 'image2'....
array1

In [ ]:
new = array1.reshape(3,5)
new

In [ ]:
array1

In [ ]:
new

In [ ]:
array_merge = numpy.hstack((new,image2))# concatinate both arrays Horizontally & and create a new one.... 
array_merge

In [ ]:
array_mergeV = numpy.vstack((new,image2))# concatinate both arrays Vertically & and create a new one.... 
array_mergeV

In [ ]:
array_mergeV.shape[0]# counts the row 

In [ ]:
split_array= numpy.hsplit(image,5)
print(split_array)

